site:
    title:        frastel@blog
    description:  Just another dev blog
    author_name:  Frank Stelzer
    author_email: dev@frankstelzer.de
    author_url:   https://twitter.com/frastel
    url_absolute: http://frastel.github.io

engine:
    themes:
        - %dir%/vendor/carew/theme-bootstrap
    extensions:
        - Carew\Plugin\Toc\TocExtension
        - Carew\Plugin\Highlight\HighlightExtension
        - Carew\Plugin\Pagination\PaginationExtension

pagination:
    max_per_page: 10
